name = "aiken-lang/hello_word"
version = "0.0.0"
compiler = "v1.1.5"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/hello_word'"

[repository]
user = "aiken-lang"
project = "hello_word"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
